[versions]
# Keep this values in sync with bundletool"s dependencies.
aapt2Proto = "7.3.0-alpha07-8248216"
protobufJava = "3.10.0"
guava = "30.1-jre"

[libraries]
dalvikDx = "com.jakewharton.android.repackaged:dalvik-dx:11.0.0_r3"
binaryResources = "com.android.tools.apkparser:binary-resources:30.4.2"
apkSigner = "com.android.tools.build:apksig:7.4.2"
bundleTool = "com.android.tools.build:bundletool:1.14.1"
aapt2Proto = { module = "com.android.tools.build:aapt2-proto", version.ref = "aapt2Proto" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
clikt = "com.github.ajalt.clikt:clikt:3.5.2"
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.3"
okio = "com.squareup.okio:okio:3.2.0"
byteunits = "com.jakewharton.byteunits:byteunits:0.9.1"
asm = "org.ow2.asm:asm:9.3"
diffUtils = "io.github.java-diff-utils:java-diff-utils:4.12"
picnic = "com.jakewharton.picnic:picnic:0.6.0"
r8 = "com.android.tools:r8:3.3.75"

[plugins]
dokka = "org.jetbrains.dokka:1.7.10"
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.7.10"
kotlinter = "org.jmailen.kotlinter:3.12.0"
mavenPublish = "com.vanniktech.maven.publish:0.22.0"
